- id: check-filenames
  name: check filenames
  description: Check for unsafe filenames
  entry: check_filenames.py
  language: python
- id: check-chars
  name: check chars
  description: Mark lines containing invalid characters
  entry: check_chars.py
  language: python
  types:
    - text
- id: check-line-length
  name: check line length
  description: Mark lines greater than 80 columns
  entry: check-line-length.sh
  language: system
  types:
    - text
