- id: check-chars
  name: check chars
  description: Mark lines containing invalid characters
  entry: check-chars
  language: python
  types:
    - text
  exclude_types:
    - makefile
- id: check-filenames
  name: check filenames
  description: Check for unsafe filenames
  entry: check-filenames
  language: python
  types:
    - file
- id: check-line-length
  name: check line length
  description: Mark lines longer than 80 characters
  entry: check-line-length
  language: python
  types:
    - text
- id: fix-leading-spaces
  name: fix leading spaces
  description: Make sure that each line begins with a multiple of 4 spaces
  entry: fix-leading-spaces
  language: python
  types:
    - text
  exclude_types:
    - yaml
